apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: product-crud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 000000000000.dkr.ecr.us-east-1.localhost.localstack.cloud:4566/product-crud-frontend:latest
        ports:
        - containerPort: 80
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 5
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 5